name: CI Workflow

on:
  pull_request:
    branches: ['*']

  push:
    branches: ['*']

jobs:
  run-tests:
    permissions: write-all
    runs-on: ubuntu-20.04

    env:
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_USER: ${{secrets.DB_USER}}
      DB_HOST: ${{secrets.DB_HOST}}
      FIREBASE_API_KEY: mock
      FIREBASE_AUTH_DOMAIN: mock
      FIREBASE_PROJECT_ID: mock
      FIREBASE_STORAGE_BUCKET: mock
      FIREBASE_MESSAGING_SENDER_ID: mock
      FIREBASE_APP_ID: mock
      FIREBASE_MEASUREMENT_ID: mock

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.DB_PASSWORD}}
          MYSQL_DATABASE: ${{secrets.DB_NAME}}
        ports:
          - 3306:3306
        volumes:
          - ./data/mysql/:/var/lib/mysql

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Build and Tests
        run: |
          npm run build
          npm run test
